---
title: Phil's Test Site
timezone: UTC
collections:
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: post
    permalink: "/projects/:title/"
    client_name: ""
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
